### PR TITLE
Feature/share image from footer

### PR DESCRIPTION
**Pull request by hasevr**
Share image from footer has implemented. I think one image at once is better. But current upload dialog supports multiple image.
To upload multiple image, need multiple pasted contents or we have to directly share the images  .

### CODE REVIEW

**Comment by zlguo1996** [comment]
I tried both ctrl+v and share image dialog, but noting happened. Image is not shown on map.

**Comment by hasevr** [comment]
Sorry. I've failed to commit some files and lost the changes also. I've fix them.
Now it works.

**Comment by zlguo1996** [comment]
> Sorry. I've failed to commit some files and lost the changes also. I've fix them.
> Now it works.

The image share dialog works now. But ctrl+v still not work.

**Comment by hasevr** [comment]
I confirm it works in my environment. If code is OK. I'll merge it to master.

**Comment by zlguo1996** [comment]
Thank you @hasevr . The code is ok.

**Pull request merged**
