### PR TITLE
Feature/mute by fab

### PR DESCRIPTION
**Pull request by hasevr**
I've tried to implement mute function. 
I'm not sure about file location, way of import from the top level index.tsx, way to access APIs. So please review it.
I also be aware an issue on avatar. It does not back to image avatar. What I do is just set false to the avatar stream. But this was not enough.

### CODE REVIEW

**Comment by zlguo1996** [comment]
I would recommend to use the state in participant store. 
- For rendering, both local and remote participant have the problem to render video / audio or not. I put perceptibility in MapObject for this. 
- As for control, we'd better not use same state as rendering (perceptibility). I put plugins.streamControl for that. 
The reason not using same state is because: [remote stream is visible] = [user not mute remote video] && [remote participant is not far from user].

**Comment by hasevr** [comment]
@zlguo1996 I don't fully understand about " I put plugins.streamControl for that."
Did you already add or you will add it ?
The problem is only on the participant component switch  ?
Are others OK ?

**Comment by zlguo1996** [comment]
I've already added it in the store. Just like I refactoring your sharedContents into plugins.contents. `services\conference\src\scripts\stores\participants\plugins\index.ts`

About the reason that image is not show: `!stream.getVideoTracks()[0].enabled` is not from store, so the component would not be re-rendered when the value is changed.

And I think the middleware file place and way of accessing APIs in middleware is ok.

**Comment by hasevr** [comment]
Thank you for the details. Now I fully understand.
I'll fix the way to modify the stream.

Shoichi


2020年6月30日(火) 0:22 Guo Zile <notifications@github.com>:

**Comment by hasevr** [comment]
I've made revised pull request and close this.

**Pull request closed without merging**
